### PR TITLE
add lang fr

### PR DESCRIPTION
**Pull request by ghost**
- add directory lang
- add lang fr-FR

### CODE REVIEW

**Comment by DennisSuitters** [comment]
You are aware that the Classes, and their associated names can be changed to suite what classes you want to use?

**Comment by cadot-info** [comment]
i have created similar lang same your other plug-ins for summernote.

**Comment by DennisSuitters** [comment]
That's cool and appreciated, but what I was referring to was this plugin. They Classes/Names aren't rigid, they could change, and mostly likely will for the upcoming release of Summernote where we are looking at not having the Bootstrap versions (but will work with Bootstrap and other CSS Frameworks). The idea of this plugin was to allow site administrators to allow content editors to have a set of custom classes that fit, and work with the website's styling, for e.g. adding classes to the first paragraph for a particular look, like having the text in that paragraph a different size or colour, and only applied to the paragraph.

**Comment by cadot-info** [comment]
Yes, for me, i like this plug because he remember for me the possibility of class.
For my users, i would like the class name translate in text comprehensive for humans ... not geek ;-)

**Comment by DennisSuitters** [comment]
All good then, and yeah, I get the easy to understand thing.

**Pull request merged**
